### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by cclementous** [hw-cookbooks/auditd#16]
I want to use [Sourcegraph](https://sourcegraph.com) for auditd code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/hw-cookbooks/auditd. (It should only take 30 seconds.)

Thank you!

**Comment by chrisroberts** [comment]
Please feel free to fork this repo and enable it on your fork. Thanks.
